a = 2
b = 2

try:
    print(a/b)
except:
    print("Não é perimitido divisão por 0")

# O python faz o tratamento e continua a execução mesmo com erro